#
# Build stage
#
FROM maven:3.8.3-amazoncorretto-20 AS build
COPY . .
RUN mvn clean package -Pprod

#
# Package stage
#
FROM amazoncorretto:20
COPY src/cert.pfx /app/cert.pfx
COPY --from=build /target/empresas-java-0.0.1-SNAPSHOT.war /app/app.war
# ENV PORT=8888
EXPOSE 9999
#CMD ["java", "-jar", "/app/app.war" , ">", "/dev/null", "2>&1", "&"]
#ENTRYPOINT ["java", "-jar", "/app/app.war"]
CMD ["java", "-jar", "/app/app.war"]
